version: "3"

volumes:
  sonarqube_db:
    external: false

networks:
  sonar_newtwork:
    external: false

services: 
  db:
    build: 
      dockerfile: Dockerfile
      context: .
    volumes:
      - sonarqube_db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - sonar_newtwork
    environment: 
      - POSTGRES_PASSWORD=qwerty
    
    
  sonar:
    image: sonarqube:7.1
    ports:
      - "9000:9000"
      - "9092:9092"
    networks:
      - sonar_newtwork
    environment: 
      - SONARQUBE_JDBC_USERNAME=sonarqube
      - SONARQUBE_JDBC_PASSWORD=qwerty
      - SONARQUBE_JDBC_URL=jdbc:postgresql://db/sonarqube