version: "3"

networks:
  marketplace:
    external: true

volumes:
  marketplacedb:
    external: true

services:
  db:
    container_name: marketplace.db
    build:
      dockerfile: Dockerfile
      context: .
    networks:
      - marketplace
    volumes:
      - marketplacedb:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

  adminer:
    image: adminer
    links:
      - db
    ports:
      - 8080:8080
    networks:
      - marketplace
