version: "3"

volumes:
  marketplace_monitor:
    external: true

networks:
  marketplace:
    external: true

services: 

  influx:
    container_name: marketplace.influxdb
    image: influxdb:1.5-alpine
    volumes:
      - "marketplace_monitor:/var/lib/influxdb"
    networks:
      - marketplace
    env_file: influxdb.env
    ports:
      - "8086:8086"
  
  diamond:
    container_name: marketplace.diamond
    image: lesaux/diamond-containercollector
    networks: 
      - marketplace
    env_file: diamond.env