version: "3"

networks:
  marketplace:
    external: true

services:
  front-nginx:
    container_name: marketplace.nginx
    build:
      dockerfile: Dockerfile
      context: ./
    ports:
      - "80:80"
    environment:
      - ENV=development
    networks:
      - marketplace
