version: "3"

networks:
  marketplace:
    external: true

volumes:
  marketplacedb:
    external: true

services:
  db:
    container_name: marketplace.db
    build:
      dockerfile: Dockerfile
      context: .
    networks:
      - marketplace
    volumes:
      - marketplacedb:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
