version: "3"

networks:
  marketplace:
    external: true

services:
  front-nginx:
    container_name: marketplace.nginx
    build:
      dockerfile: Dockerfile
      context: ./
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
    ports:
      - "80:80"
      - "443:443"
    environment:
      - ENV=development
