version: "3"

networks:
  marketplace:
    external: true

services:
  app:
    build:
      dockerfile: Dockerfile
      context: .
      args:
        - CELERY_BROKER_URL
        - CELERY_BACKEND_URL
        - FLASK_ENV
        - SQLALCHEMY_DATABASE_URI
        - SECRET_KEY
        - SECURITY_PASSWORD_SALT
        - FLASK_DEBUG
        - UPLOAD_FOLDER
        - CACHE_STORAGE_HOST
    environment:
      - FLASK_DEBUG=${FLASK_DEBUG}
      - FLASK_ENV=${FLASK_ENV}
      - SQLALCHEMY_DATABASE_URI=${SQLALCHEMY_DATABASE_URI}
      - CELERY_BROKER_URL=${CELERY_BROKER_URL}
      - CELERY_BACKEND_URL=${CELERY_BACKEND_URL}
      - SECRET_KEY=#{SECRET_KEY}
      - SECURITY_PASSWORD_SALT=${SECURITY_PASSWORD_SALT}
      - UPLOAD_FOLDER=${UPLOAD_FOLDER}
      - CACHE_STORAGE_HOST=${CACHE_STORAGE_HOST}
    ports:
      - "8000:8000"
    command:
      "flask run --port=8000 --host=0.0.0.0"
    networks:
      - marketplace
    volumes:
      - "./marketplace/:/app/marketplace"


  redis:
    image: redislabs/rejson:latest
    networks:
      - marketplace


  celery:
    container_name: marketplace.celery
    build:
      dockerfile: Dockerfile
      context: .
      args:
        - FLASK_DEBUG
        - FLASK_ENV
        - CELERY_BROKER_URL
        - CELERY_BACKEND_URL
        - SQLALCHEMY_DATABASE_URI
        - SECRET_KEY
        - SECURITY_PASSWORD_SALT
        - UPLOAD_FOLDER
        - CELERY_APP
        - SENTRY_DSN
        - CACHE_STORAGE_HOST
    command:
      "celery -A marketplace.celery --loglevel=info worker -B"
    networks:
      - marketplace
    environment:
      - FLASK_DEBUG=${FLASK_DEBUG}
      - FLASK_ENV=${FLASK_ENV}
      - CELERY_BROKER_URL=${CELERY_BROKER_URL}
      - CELERY_BACKEND_URL=${CELERY_BACKEND_URL}
      - SECRET_KEY=#{SECRET_KEY}
      - SECURITY_PASSWORD_SALT=${SECURITY_PASSWORD_SALT}
      - SQLALCHEMY_DATABASE_URI=${SQLALCHEMY_DATABASE_URI}
      - UPLOAD_FOLDER=${UPLOAD_FOLDER}
      - CELERY_APP=True
      - SENTRY_DSN=${SENTRY_DSN}
      - CACHE_STORAGE_HOST=${CACHE_STORAGE_HOST}
    volumes:
      - "./marketplace/:/app/marketplace"
    depends_on:
      - redis
