version: "3"

networks:
  marketplace:
    external: true

# volumes:
#   marketplaceapp:
#     external: true

services:
  app:
    build:
      dockerfile: Dockerfile
      context: .
      args:
        - CELERY_BROKER_URL
        - FLASK_DEBUG
    environment:
      - FLASK_DEBUG=${FLASK_DEBUG}
      - SQLALCHEMY_DATABASE_URI=${SQLALCHEMY_DATABASE_URI}
    ports:
      - "8000:8000"
    command:
      "flask run --port=8000 --host=0.0.0.0"
    networks:
      - marketplace
    volumes:
      # - ".:/app"
      - "./marketplace/:/app/marketplace"


  redis:
    image: redis:5.0-rc
    networks:
      - marketplace


  celery:
    build:
      dockerfile: Dockerfile
      context: .
      args:
        - CELERY_BROKER_URL
    volumes:
      # - ".:/app"
      - "./marketplace/:/app/marketplace"
    command:
      "celery -A marketplace.celery --loglevel=info worker"
    networks:
      - marketplace
    environment:
      - CELERY_BROKER_URL=${CELERY_BROKER_URL}
    depends_on:
      - redis
      - app
