version: "3"

networks:
  marketplace:
    external: true

volumes:
  marketplace_user_image:
    external: true

services:
  app:
    container_name: marketplace.app
    build:
      dockerfile: Dockerfile
      context: .
      args:
        - CELERY_BROKER_URL
        - FLASK_ENV
        - SQLALCHEMY_DATABASE_URI
        - SECRET_KEY
        - SECURITY_PASSWORD_SALT
    environment:
      - FLASK_ENV=production
      - SQLALCHEMY_DATABASE_URI=${SQLALCHEMY_DATABASE_URI}
      - CELERY_BROKER_URL=${CELERY_BROKER_URL}
      - SECRET_KEY=#{SECRET_KEY}
      - SECURITY_PASSWORD_SALT=${SECURITY_PASSWORD_SALT}
    ports:
      - "10.100.1.39:8000:8000"
    command:
      "flask run --port=8000 --host=0.0.0.0"
    networks:
      - marketplace
    volumes:
      - "marketplace_user_image:/app/marketplace/user_images"


  redis:
    container_name: marketplace.redis
    image: redislabs/rejson:latest
    networks:
      - marketplace


  celery:
    container_name: marketplace.celery
    build:
      dockerfile: Dockerfile
      context: .
      args:
        - CELERY_BROKER_URL
    command:
      "celery -A marketplace.celery --loglevel=info worker"
    networks:
      - marketplace
    environment:
      - CELERY_BROKER_URL=${CELERY_BROKER_URL}
    depends_on:
      - redis
      - app
