version: "3"

networks:
  marketplace:
    external: true

volumes:
  marketplace_user_image:
    external: true
  marketplace_tasts:
    external: true


services:
  app:
    container_name: marketplace.app
    build:
      dockerfile: Dockerfile
      context: .
      args:
        - CELERY_BROKER_URL
        - CELERY_BACKEND_URL
        - FLASK_ENV
        - SQLALCHEMY_DATABASE_URI
        - SECRET_KEY
        - SECURITY_PASSWORD_SALT
        - UPLOAD_FOLDER
    environment:
      - FLASK_ENV=production
      - SQLALCHEMY_DATABASE_URI=${SQLALCHEMY_DATABASE_URI}
      - CELERY_BROKER_URL=${CELERY_BROKER_URL}
      - CELERY_BACKEND_URL=${CELERY_BACKEND_URL}
      - SECRET_KEY=#{SECRET_KEY}
      - SECURITY_PASSWORD_SALT=${SECURITY_PASSWORD_SALT}
      - UPLOAD_FOLDER=${UPLOAD_FOLDER}
    ports:
      - "10.100.1.39:8000:8000"
    command:
      "flask run --port=8000 --host=0.0.0.0"
    networks:
      - marketplace
    volumes:
      - "marketplace_user_image:${UPLOAD_FOLDER}"


  redis:
    container_name: marketplace.redis
    image: redislabs/rejson:latest
    networks:
      - marketplace
    volumes:
      - "marketplace_tasts: /data"


  celery:
    container_name: marketplace.celery
    build:
      dockerfile: Dockerfile
      context: .
      args:
        - CELERY_BROKER_URL
        - CELERY_BACKEND_URL
        - UPLOAD_FOLDER
        - SQLALCHEMY_DATABASE_URI
        - SECRET_KEY
        - SECURITY_PASSWORD_SALT
        - CELERY_APP
    command:
      "celery -A marketplace.celery --loglevel=info worker"
    networks:
      - marketplace
    environment:
      - CELERY_BROKER_URL=${CELERY_BROKER_URL}
      - CELERY_BACKEND_URL=${CELERY_BACKEND_URL}
      - UPLOAD_FOLDER=${UPLOAD_FOLDER}
      - SECRET_KEY=#{SECRET_KEY}
      - SECURITY_PASSWORD_SALT=${SECURITY_PASSWORD_SALT}
      - SQLALCHEMY_DATABASE_URI=${SQLALCHEMY_DATABASE_URI}
      - CELERY_APP=True
    volumes:
      - "marketplace_user_image:${UPLOAD_FOLDER}"
    depends_on:
      - redis
