version: "3"

networks:
  marketplace:
    external: true

volumes:
  marketplace_user_image:
    external: true
  marketplace_tasks:
    external: true


services:
  app:
    container_name: marketplace.app
    build:
      dockerfile: Dockerfile
      context: .
      args:
        - CELERY_BROKER_URL
        - CELERY_BACKEND_URL
        - FLASK_ENV
        - SQLALCHEMY_DATABASE_URI
        - SECRET_KEY
        - SECURITY_PASSWORD_SALT
        - UPLOAD_FOLDER
        - SENTRY_DSN
        - MAIL_PASSWORD
        - INFLUXDB_WRITE_USER
        - INFLUXDB_WRITE_USER_PASSWORD
        - CACHE_STORAGE_HOST
    environment:
      - FLASK_ENV=production
      - SQLALCHEMY_DATABASE_URI=${SQLALCHEMY_DATABASE_URI}
      - CELERY_BROKER_URL=${CELERY_BROKER_URL}
      - CELERY_BACKEND_URL=${CELERY_BACKEND_URL}
      - SECRET_KEY=${SECRET_KEY}
      - SECURITY_PASSWORD_SALT=${SECURITY_PASSWORD_SALT}
      - UPLOAD_FOLDER=${UPLOAD_FOLDER}
      - SENTRY_DSN=${SENTRY_DSN}
      - MAIL_PASSWORD=${MAIL_PASSWORD}
      - INFLUXDB_WRITE_USER=${INFLUXDB_WRITE_USER}
      - INFLUXDB_WRITE_USER_PASSWORD=${INFLUXDB_WRITE_USER_PASSWORD}
      - CACHE_STORAGE_HOST=${CACHE_STORAGE_HOST}
    ports:
      - "10.100.1.39:8000:8000"
    command:
      "flask run --port=8000 --host=0.0.0.0"
    networks:
      - marketplace
    volumes:
      - "marketplace_user_image:${UPLOAD_FOLDER}"
    restart: on-failure


  redis:
    container_name: marketplace.redis
    image: redislabs/rejson:latest
    networks:
      - marketplace
    volumes:
      - "marketplace_tasks:/data"
    restart: on-failure


  celery:
    container_name: marketplace.celery
    build:
      dockerfile: Dockerfile
      context: .
      args:
        - CELERY_BROKER_URL
        - CELERY_BACKEND_URL
        - UPLOAD_FOLDER
        - SQLALCHEMY_DATABASE_URI
        - SECRET_KEY
        - SECURITY_PASSWORD_SALT
        - CELERY_APP
        - SENTRY_DSN
        - MAIL_PASSWORD
        - INFLUXDB_WRITE_USER
        - INFLUXDB_WRITE_USER_PASSWORD
        - CACHE_STORAGE_HOST
    command:
      "celery -A marketplace.celery --loglevel=info worker -B"
    networks:
      - marketplace
    environment:
      - CELERY_BROKER_URL=${CELERY_BROKER_URL}
      - CELERY_BACKEND_URL=${CELERY_BACKEND_URL}
      - UPLOAD_FOLDER=${UPLOAD_FOLDER}
      - SECRET_KEY=${SECRET_KEY}
      - SECURITY_PASSWORD_SALT=${SECURITY_PASSWORD_SALT}
      - SQLALCHEMY_DATABASE_URI=${SQLALCHEMY_DATABASE_URI}
      - CELERY_APP=True
      - SENTRY_DSN=${SENTRY_DSN}
      - MAIL_PASSWORD=${MAIL_PASSWORD}
      - INFLUXDB_WRITE_USER=${INFLUXDB_WRITE_USER}
      - INFLUXDB_WRITE_USER_PASSWORD=${INFLUXDB_WRITE_USER_PASSWORD}
      - CACHE_STORAGE_HOST=${CACHE_STORAGE_HOST}
    volumes:
      - "marketplace_user_image:${UPLOAD_FOLDER}"
    depends_on:
      - redis
    restart: on-failure
